language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=settings

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Set Travis builds to use docker container
sudo: false

install:
    - npm install
    - "pip install -r local_requirements.txt"
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
    - "pip install coveralls"

script:
    - make test

after_success: coveralls
